-- APEX Application 100 Export Placeholder
-- Generated by APEX Export tool (JSON / SQL)
PROMPT Installing APEX Application 100...
BEGIN
  NULL; -- Placeholder for APEX Application DDL / Export package
END;
/
