version: '3.8'

services:
  db-apex-proxy:
    image: container-registry.oracle.com/database/adb-free:latest
    environment:
      - WORKLOAD_TYPE=ATP
      - ADMIN_PASSWORD=VWKSxcgwocxl8576rw6L
      - WALLET_PASSWORD=FKATiaqjxriu9591HE1c
