version: '3.8'

services:
  db-apex-proxy:
    image: container-registry.oracle.com/database/adb-free:latest
    environment:
      - WORKLOAD_TYPE=ATP
      - ADMIN_PASSWORD=JFJFzgfvtcau8972U6u9
      - WALLET_PASSWORD=RYAQrgjotxrh2486xKAP
