profile:
  id: app-ords-external
  name: app-ords-external
  description: "External Corporate ORDS Server profile for remote database mapping."
  type: application
  component: ords

ords:
  enabled: true
  is_external: true
  http_port: 8080
  https_port: 8443
  external_host: "ords.corp.internal"
