profile:
  id: app-ords-image
  name: app-ords-image
  description: "Standard Central Multi-Pool ORDS Server using official Oracle ORDS container image."
  type: application
  component: ords

ords:
  enabled: true
  version: "26.2.2"
  container_image: container-registry.oracle.com/database/ords:latest
  container_name: app-ords
  service_name: app-ords
  download_url: "https://download.oracle.com/otn_software/java/ords/ords-latest.zip"
  http_port: 8088
  https_port: 8448
  standalone_mode: false
  install_type: image
