profile:
  id: publisher-remote-linux
  name: publisher-remote-linux
  description: "Remote Enterprise Linux Oracle Analytics Publisher Server profile."
  type: middleware
  component: publisher

publisher:
  enabled: true
  mode: remote-linux
  version: "2025"
  remote_host: "10.0.1.50"
  remote_user: "oracle"
  http_port: 9502
  https_port: 9503
  admin_port: 9500
  admin_username: weblogic
  target_database: "db-publisher"
  rcu_prefix: "OAS"
