profile:
  id: publisher-container
  name: publisher-container
  description: "Standard Oracle Analytics Publisher 2025/2026 container profile running in dedicated WebLogic domain."
  type: middleware
  component: publisher

publisher:
  enabled: true
  mode: container
  version: "2025"
  container_image: localhost/oracle/analyticsserver:2025
  container_name: oracle-publisher-dev
  hostname: publisher-dev
  http_port: 9502
  https_port: 9503
  admin_port: 9500
  admin_username: weblogic
  target_database: "db-publisher"
  rcu_prefix: "OAS"
  configure_biee: false
  configure_bip: true
  memory_args: "-Xms1024m -Xmx2048m -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m"
