# ==============================================================================
# Oracle DevOps Platform - Enterprise WSL2 Environment Auto-Configurator
# Purpose: Tunes %USERPROFILE%\.wslconfig for Oracle 23ai + APEX + ORDS workloads,
#          exports corporate proxy CA certs into WSL2, and prevents VPN DNS loss.
# Privileges: 100% standard user (0-Admin / No UAC required).
# ==============================================================================
[CmdletBinding()]
param(
    [int]$MemoryGB = 0,
    [switch]$SkipCerts,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

Write-Host "==================================================================" -ForegroundColor Cyan
Write-Host "  ORACLE DEVOPS PLATFORM - ENTERPRISE WSL2 CONFIGURATOR" -ForegroundColor Cyan
Write-Host "==================================================================" -ForegroundColor Cyan

# 1. Inspect Host Resources
$os = Get-CimInstance Win32_OperatingSystem
$totalHostRamGB = [math]::Round($os.TotalVisibleMemorySize / 1024 / 1024)
$logicalCores = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors

Write-Host "[INFO] Detected Host Resources:" -ForegroundColor Yellow
Write-Host "       Total Host RAM:  $totalHostRamGB GB"
Write-Host "       Logical Cores:   $logicalCores"

# 2. Determine Optimal WSL2 Memory & Processors
if ($MemoryGB -le 0) {
    # Allocate 50% of host RAM, minimum 6 GB, maximum 16 GB for standard dev
    $targetRamGB = [math]::Max(6, [math]::Min(16, [math]::Round($totalHostRamGB * 0.5)))
    if ($totalHostRamGB -lt 12) {
        Write-Host "[WARNING] Host RAM ($totalHostRamGB GB) is below the recommended 16 GB." -ForegroundColor Yellow
        Write-Host "          Setting WSL2 memory to 6 GB. High-RAM blueprints (Forms, Publisher) may struggle." -ForegroundColor Yellow
        $targetRamGB = 6
    }
} else {
    $targetRamGB = $MemoryGB
}

$targetProcessors = [math]::Max(2, $logicalCores - 2)
Write-Host "[INFO] Target WSL2 Allocation:" -ForegroundColor Green
Write-Host "       RAM for WSL2:    $targetRamGB GB"
Write-Host "       Processors:      $targetProcessors"

# 3. Generate or Update %USERPROFILE%\.wslconfig
$wslConfigPath = Join-Path $env:USERPROFILE ".wslconfig"
$isWin11 = ([System.Environment]::OSVersion.Version.Build -ge 22000)

$wslConfigContent = @"
# ==============================================================================
# Oracle DevOps Platform - Optimized WSL2 Configuration
# Auto-generated by scripts/wsl/configure-wsl-enterprise.ps1
# ==============================================================================
[wsl2]
memory=${targetRamGB}GB
processors=${targetProcessors}
swap=4GB
localhostForwarding=true
nestedVirtualization=true

"@

if ($isWin11) {
    $wslConfigContent += @"
# Windows 11 Enterprise Network & Corporate VPN Enhancements
networkingMode=mirrored
dnsTunneling=true
autoProxy=true

"@
    Write-Host "[INFO] Windows 11 detected: Enabled 'mirrored' networking & DNS tunneling (fixes VPN dropouts)." -ForegroundColor Green
}

if ((Test-Path $wslConfigPath) -and -not $Force) {
    $backupPath = "$wslConfigPath.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item $wslConfigPath $backupPath
    Write-Host "[INFO] Existing .wslconfig backed up to: $backupPath" -ForegroundColor Gray
}

Set-Content -Path $wslConfigPath -Value $wslConfigContent -Encoding UTF8
Write-Host "✅ .wslconfig successfully written to: $wslConfigPath" -ForegroundColor Green

# 4. Corporate Proxy Root CA Certificate Export
if (-not $SkipCerts) {
    Write-Host ""
    Write-Host "==================================================================" -ForegroundColor Cyan
    Write-Host "  CORPORATE PROXY / ZSCALER CA EXPORT TO WSL2" -ForegroundColor Cyan
    Write-Host "==================================================================" -ForegroundColor Cyan

    $tempCertDir = Join-Path $env:TEMP "oracle_devops_certs"
    if (-not (Test-Path $tempCertDir)) {
        New-Item -ItemType Directory -Path $tempCertDir -Force | Out-Null
    }

    $exportedCertPath = Join-Path $tempCertDir "corporate_roots.pem"
    if (Test-Path $exportedCertPath) { Remove-Item $exportedCertPath -Force }

    $rootCerts = Get-ChildItem -Path Cert:\CurrentUser\Root, Cert:\LocalMachine\Root -ErrorAction SilentlyContinue |
                 Where-Object { $_.Issuer -match 'Zscaler|Netskope|Corp|Enterprise|Proxy|Security|Palo Alto' }

    if ($rootCerts -and $rootCerts.Count -gt 0) {
        Write-Host "[INFO] Found $($rootCerts.Count) corporate root certificate(s) in Windows store." -ForegroundColor Yellow
        $pemContent = ""
        foreach ($cert in $rootCerts) {
            $bytes = $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert)
            $base64 = [System.Convert]::ToBase64String($bytes, [System.Base64FormattingOptions]::InsertLineBreaks)
            $pemContent += "# Subject: $($cert.Subject)`n-----BEGIN CERTIFICATE-----`n$base64`n-----END CERTIFICATE-----`n`n"
        }
        Set-Content -Path $exportedCertPath -Value $pemContent -Encoding ASCII
        Write-Host "       Exported to: $exportedCertPath" -ForegroundColor Gray

        # Import into WSL2 if wsl.exe is available
        if (Get-Command wsl.exe -ErrorAction SilentlyContinue) {
            $wslWinPath = (wsl.exe wslpath -u ($exportedCertPath -replace '\\', '/')).Trim()
            wsl.exe bash -c "
                if [ -d /usr/local/share/ca-certificates ]; then
                    sudo cp '$wslWinPath' /usr/local/share/ca-certificates/corporate_roots.crt 2>/dev/null && sudo update-ca-certificates >/dev/null 2>&1 || true
                fi
                mkdir -p ~/.config/certs 2>/dev/null || true
                cp '$wslWinPath' ~/.config/certs/corporate_roots.pem 2>/dev/null || true
            " 2>$null
            Write-Host "✅ Corporate proxy certificates injected into WSL2 store." -ForegroundColor Green
        }
    } else {
        Write-Host "[INFO] No explicit Zscaler/Netskope certificates found. Skipping proxy CA export." -ForegroundColor Gray
    }
}

Write-Host ""
Write-Host "==================================================================" -ForegroundColor Cyan
Write-Host "🎉 WSL2 ENTERPRISE CONFIGURATION COMPLETE!" -ForegroundColor Green
Write-Host "   To apply changes, restart WSL in PowerShell with:" -ForegroundColor Yellow
Write-Host "   👉 wsl --shutdown" -ForegroundColor White
Write-Host "   Then launch: setup.cmd or ./scripts/setup-all.sh" -ForegroundColor White
Write-Host "==================================================================" -ForegroundColor Cyan
