-- =============================================================================
-- Passive Core Business Database: Transactional Outbox Pattern DDL
-- Security Invariant: The Business DB NEVER initiates outbound connections.
-- It records outbound events transactionally within its local schema.
-- The DMZ Proxy DB / Middleware layer polls and dispatches the events.
-- =============================================================================

-- 1. Outbox Events Table
CREATE TABLE outbox_events (
    event_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type  VARCHAR2(64) NOT NULL,
    aggregate_id    VARCHAR2(128) NOT NULL,
    event_type      VARCHAR2(64) NOT NULL,
    topic_name      VARCHAR2(128) NOT NULL,
    payload_json    CLOB NOT NULL,
    status          VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    retry_count     NUMBER DEFAULT 0 NOT NULL,
    error_message   VARCHAR2(4000),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    processed_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_outbox_status CHECK (status IN ('PENDING', 'PROCESSING', 'PUBLISHED', 'FAILED'))
);

CREATE INDEX idx_outbox_status_created ON outbox_events(status, created_at);
CREATE INDEX idx_outbox_aggregate ON outbox_events(aggregate_type, aggregate_id);

-- 2. Core Outbox Producer Package Specification
CREATE OR REPLACE PACKAGE pkg_outbox AS
    -- Enqueue event inside the same database transaction as the business operation
    PROCEDURE publish_event(
        p_aggregate_type IN VARCHAR2,
        p_aggregate_id   IN VARCHAR2,
        p_event_type     IN VARCHAR2,
        p_topic_name     IN VARCHAR2,
        p_payload_json   IN CLOB,
        p_event_id       OUT NUMBER
    );

    -- Status updates called exclusively by authorized proxy / poller
    PROCEDURE mark_processing(p_event_id IN NUMBER);
    PROCEDURE mark_published(p_event_id IN NUMBER);
    PROCEDURE mark_failed(p_event_id IN NUMBER, p_error_message IN VARCHAR2);
END pkg_outbox;
/

-- 3. Core Outbox Producer Package Body
CREATE OR REPLACE PACKAGE BODY pkg_outbox AS

    PROCEDURE publish_event(
        p_aggregate_type IN VARCHAR2,
        p_aggregate_id   IN VARCHAR2,
        p_event_type     IN VARCHAR2,
        p_topic_name     IN VARCHAR2,
        p_payload_json   IN CLOB,
        p_event_id       OUT NUMBER
    ) IS
    BEGIN
        INSERT INTO outbox_events (
            aggregate_type,
            aggregate_id,
            event_type,
            topic_name,
            payload_json,
            status
        ) VALUES (
            p_aggregate_type,
            p_aggregate_id,
            p_event_type,
            p_topic_name,
            p_payload_json,
            'PENDING'
        ) RETURNING event_id INTO p_event_id;
    END publish_event;

    PROCEDURE mark_processing(p_event_id IN NUMBER) IS
    BEGIN
        UPDATE outbox_events
           SET status = 'PROCESSING'
         WHERE event_id = p_event_id;
    END mark_processing;

    PROCEDURE mark_published(p_event_id IN NUMBER) IS
    BEGIN
        UPDATE outbox_events
           SET status = 'PUBLISHED',
               processed_at = SYSTIMESTAMP
         WHERE event_id = p_event_id;
    END mark_published;

    PROCEDURE mark_failed(p_event_id IN NUMBER, p_error_message IN VARCHAR2) IS
    BEGIN
        UPDATE outbox_events
           SET status = 'FAILED',
               retry_count = retry_count + 1,
               error_message = SUBSTR(p_error_message, 1, 4000)
         WHERE event_id = p_event_id;
    END mark_failed;

END pkg_outbox;
/
