profile:
  id: db-infra-gvenzl
  name: db-infra-gvenzl
  description: "Oracle Infrastructure DB for Oracle Analytics Publisher and Oracle Forms (RCU schemas, high processes=1000) running on Gvenzl faststart container image."
  functionality: appinfra
  db_type: standard
  image_vendor: gvenzl

database:
  container_image: docker.io/gvenzl/oracle-free:23-full-faststart
  workload_type: NONE
  admin_user: sys
  admin_role: SYSDBA
  default_service: FREEPDB1
  db_port: 1534
  wallet_required: false
  configure_tde: true
  encrypt_tablespaces: ALL
  kafka_bootstrap_servers: "localhost:9092"

components:
  ords:
    enabled: true
    container_name: app-ords
    service_name: app-ords
    http_port: 8088
    https_port: 8448
  apex:
    enabled: false

users:
  - username: sys
    role: SYSDBA
    wallet_alias: DB_INFRA_SYS
    color: "#E74C3C"
  - username: DEV_FULL
    role: RCU_OWNER
    wallet_alias: DB_INFRA_RCU
    color: "#2980B9"
